import { Inter } from "next/font/google";
import "./globals.css";
import {neobrutalism} from "@clerk/themes";

import {
  ClerkProvider
} from '@clerk/nextjs'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: neobrutalism,
        layout: {
          socialButtonsPlacement: 'bottom',
          ButtonsVariant: 'iconButton',
          helpPageUrl:'https://profile-lime-two.vercel.app/',
          socialButtonsPlacement:'top'
        }
      }}>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
